name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SOLUTION_PATH: 'TournamentAPI.sln'

jobs:
  update-lock-files:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Regenerate lock files
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Git
        run: |
          git diff --quiet "**/packages.lock.json" && echo "Nothing to commit" && exit 0
          git config user.name "github-actions[bot]"
          git config user.email "<>"
          git add "**/packages.lock.json"
          git commit -m "chore: regenerate packages.lock.json"
          git push

  build-test:
    needs: update-lock-files
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }} --locked-mode

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test (Unit)
        run: dotnet test TournamentAPI.UnitTests/TournamentAPI.UnitTests.csproj --configuration Release --no-restore --no-build

      - name: Test (Integration)
        env:
          HealthCheck__ApiKey: ${{ secrets.HEALTHCHECK_API_KEY }}
        run: dotnet test TournamentAPI.IntegrationTests/TournamentAPI.IntegrationTests.csproj --configuration Release --no-restore --no-build
